version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: astleta-postgres
    hostname: astleta-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: astleta
      POSTGRES_USER: astleta_user
      POSTGRES_PASSWORD: astleta_pass
    ports:
      - "5434:5432"
    volumes:
      - astleta_postgres_data:/var/lib/postgresql/data
    networks:
      astleta_network:
        aliases:
          - astleta-postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: astleta-backend
    hostname: astleta-backend
    restart: unless-stopped
    ports:
      - "7000:8000"
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - postgres
    env_file:
      - backend/.env
    networks:
      astleta_network:
        aliases:
          - astleta-backend

  redis:
    image: redis:alpine
    container_name: astleta-redis
    hostname: astleta-redis
    restart: unless-stopped
    networks:
      astleta_network:
        aliases:
          - astleta-redis

  queue-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: astleta-queue-worker
    hostname: astleta-queue-worker
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - postgres
      - redis
    env_file:
      - backend/.env
    command: ["php", "artisan", "queue:work", "--timeout=900"]
    networks:
      astleta_network:
        aliases:
          - astleta-queue-worker

  horizon:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: astleta-horizon
    hostname: astleta-horizon
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - postgres
      - redis
    env_file:
      - backend/.env
    command: ["php", "artisan", "horizon"]
    networks:
      astleta_network:
        aliases:
          - astleta-horizon

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: astleta-frontend
    hostname: astleta-frontend
    restart: unless-stopped
    ports:
      - "2222:5173"
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      astleta_network:
        aliases:
          - astleta-frontend

networks:
  astleta_network:
    driver: bridge

volumes:
  astleta_postgres_data:
    driver: local
